name = "bfhl-fullstack-exam-api"
main = "src/worker.ts"
compatibility_date = "2025-05-08"

#Durable Object for rateLimiter
[[env.production.durable_objects.bindings]]
name = "RATE_LIMITER" 
class_name = "RateLimiterDO"
[[env.production.migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiterDO"]

